version: '3.8'

services:
  mysqlsrv:
    platform: linux/x86_64
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./volume_mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - "8181:8080" # http://localhost:8181/?server=mysqlsrv
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge